[CRO-414] Update for use with `tango-and-cash`
sproutsocial/node-mm-rest-api pull request #1
Opened 2017-08-18 15:20 UTC by jritterbush

Update the script to be used with our Maxymiser test building library.

- Use `yarn` to lock down versions better
- Change out defaults endpoint from 🇪🇺  to 🇺🇸 , because we are of the class of lazy Americans who don't want to override default settings. We want to be the default.
- Add additional allowed properties to `elements` methods
- Add create method to `campaign-actions`

2017-08-21 12:37 UTC, jritterbush commented
@ericcecchi @ericmikkelsen @conwaydev and this is also a WIP, but much closer to final from what I can tell. I've modified the original a bit to make it align better with our needs and with the latest options the REST API offers.

2017-08-21 14:54 UTC, ericcecchi requested changes

2017-08-21 14:54 UTC, ericcecchi commented on __tests__/campaign-actions-test.js
>  var credentials = {
You could add a test here for the new `create` method.

2017-08-21 14:54 UTC, ericcecchi commented on README.md
> +  // elementId: 'MDMyMDU4',
`elementId` and `elementName` aren't actually part of the actions request schema.

2017-08-21 20:52 UTC, jritterbush commented on __tests__/campaign-actions-test.js
>  var credentials = {
done and passing

2017-08-22 14:14 UTC, ericmikkelsen approved these changes

2017-08-22 14:31 UTC, ericcecchi approved these changes

2017-08-25 17:22 UTC, merged